<?php

namespace App\Models\Integration\HRMIS\v9\Employee;

use Illuminate\Database\Eloquent\Model;

class EmployeePosition extends Model
{
    protected $connection = 'hrmis';
    protected $table = 'tblEmpPosition';
    protected $primaryKey = 'empID';
    public $timestamps = false;

    protected $fillable = [
        'empNumber',
        'appointmentCode',
        'statusOfAppointment',
        'positionCode',
        'serviceCode',
        'plantillaGroupCode',
        'divisionCode',
        'sectionCode',
        'taxStatCode',
        'itemNumber',
        'salaryGradeNumber',
        'authorizeSalary',
        'actualSalary',
        'contractEndDate',
        'effectiveDate',
        'positionDate',
        'longevityDate',
        'longevityGap',
        'firstDayAgency',
        'firstDayGov',
        'assignPlace',
        'stepNumber',
        'dateIncremented',
        'personnelAction',
        'employmentBasis',
        'categoryService',
        'nature',
        'hpFactor',
        'longiFactor',
        'payrollSwitch',
        'schemeCode',
        'itwSwitch',
        'lifeRetSwitch',
        'pagibigSwitch',
        'philhealthSwitch',
        'providentSwitch',
        'premiumAidSwitch',
        'dtrSwitch',
        'mcSwitch',
        'hazardSwitch',
        'longevitySwitch',
        'PERASwitch',
        'ADCOMSwitch',
        'dependents',
        'healthProvider',
        'tmpStepNumber',
        'tmpActualSalary',
        'tmpDateIncremented',
        'tmpPositionDate',
        'regularDedSwitch',
        'contriDedSwitch',
        'loanDedSwitch',
        'zonecode',
        'riceSwitch',
        'detailedfrom',
        'departmentcode',
        'groupCode',
        'firefighter',
        'security',
        'uniqueItemNumber',
        'physician',
        'officecode',
        'service',
        'payrollGroupCode',
        'taxAmount',
        'hpTax',
        'lpTax',
        'laundrySwitch',
        'addPAGIBIGContri',
        'includeSecondment',
        'group1',
        'group2',
        'group3',
        'group4',
        'group5',
        'RATACode',
        'RATAVehicle',
        'taxRate',
        'is_override',
        'override_id',
        'taxSwitch'
    ];
}
